%% Draw figures

clear; close all;
printFigures = true;

%% Figures
figureList = { ...
     'sdtModel'; ...
     % 'typeDistribution'; ...
    };


%% Load behavioral data and colors
load pantoneColors pantone;

%% Loop over figures
for figureIdx = 1:numel(figureList)
    switch figureList{figureIdx}
        
        case 'sdtModel'
            
            k = 1.75;
            dL = [0 0.75 1.5 2 2.5 3 3.5];
            
            % constants
            x = -2:.01:5.5;
            fontSize = 24;
            colors{1} = pantone.Marsala;
            baseColor{2} = pantone.Custard; baseColor{1} = pantone.DuskBlue;
            labels = {'Old', 'Lure 1', 'Lure 2', 'Lure 3', 'Lure 4', 'Lure 5', 'New'};
            dLabels = {'old', '$d_{L1}$', '$d_{L2}$', '$d_{L3}$', '$d_{L4}$', '$d_{L5}$', '$d_{new}$'};
            scale = 0.8;
            
            for idx = 2:length(dL)
                w = ((idx-1)-1)/(length(dL)-2);
                colors{idx} = w*baseColor{1} + (1-w)*baseColor{2};
            end
            
            % figure
            F = figure; clf; hold on;
            setFigure(F, [0.2 0.2 0.6 0.6], '');
            
            % axis
            set(gca, ...
                'xlim'       , x([1 end])  , ...
                'xtick'      , 0:x(end)    , ...
                'ylim'        , [0 1], ...
                'ycolor'      , 'none'    , ...
                'box'        , 'off'                 , ...
                'tickdir'    , 'out'                 , ...
                'layer'      , 'top'                 , ...
                'ticklength' , [0.01 0]              , ...
                'layer'      , 'top'                 , ...
                'fontsize'   , fontSize              );
            xlabel('Stimulus Novelty', 'fontsize', fontSize+4);
            
           for idx = 1:length(dL)
               
               y = scale*exp(-(x - dL(idx)).^2);
            patch([x(1) x x(end)], [0 y 0], 'k', ...
                'facecolor' , colors{idx}, ...
                'edgecolor' , 'w'               , ...
                'facealpha' , 0.8               );
            
               text(dL(idx), scale,  dLabels{idx}, ...
                'fontsize', fontSize+2, ...
                'vertical', 'bottom', ...
                'horizontal', 'center', ...
                'interp', 'latex');
            
           end
            
           L =  legend(labels, ...
                'fontsize', fontSize, ...
                'box', 'off', ...
                'autoupdate', 'off', ...
                'location', 'northwest');
            set(L, 'pos', get(L, 'pos') + [-0.1 0 0 0 ]);
            
            plot([k k], get(gca, 'ylim'), '-', ...
                'linewidth', 2, ...
                'color', pantone.Kale);
            
            text(k, 1, '$k$', ...
                'fontsize', fontSize+2, ...
                'vertical', 'bottom', ...
                'horizontal', 'center', ...
                'interp', 'latex');
            
             case 'typeDistribution'
            
            % data from manuel in slack (young, old, experimental)
            d = [204  67  51  87  111  53   3;
                162  107  65  59  38  104  41;
                0.333  0.070  0.068  0.065  0.067  0.062  0.333];
            n = 192;
                
            
            % constants
            fontSize = 24;
            colors = {pantone.ClassicBlue; pantone.Marsala; pantone.Custard};
            labels = {'Old', 'Lure 1', 'Lure 2', 'Lure 3', 'Lure 4', 'Lure 5', 'New'};
            nTypes = numel(labels);
            gap = 0.1;
            width = 0.5;
            
            % figure
            F = figure; clf; hold on;
            setFigure(F, [0.2 0.2 0.6 0.6], '');
            
            % axis
            set(gca, ...
                'xlim'       , [0.5 nTypes+0.5]  , ...
                'xtick'      , 1:nTypes    , ...
                'xticklabel' , labels , ...
                'ylim'        , [0 0.5], ...
                'ytick'      , 0:0.1:1  , ...
                'box'        , 'off'                 , ...
                'tickdir'    , 'out'                 , ...
                'layer'      , 'top'                 , ...
                'ticklength' , [0.01 0]              , ...
                'layer'      , 'top'                 , ...
                'fontsize'   , fontSize              );
            ylabel('Frequency', 'fontsize', fontSize+4);
            Raxes(gca, 0, 0.01);
            
            bar((1:nTypes)-gap, d(1, :)/(3*n), width, ...
                'facecolor', colors{1}, ...
                'facealpha', 0.5      , ...
                'edgecolor', 'none');
            
                        bar((1:nTypes)+gap, d(2, :)/(3*n), width, ...
                'facecolor', colors{2}, ...
                'facealpha', 0.5      , ...
                'edgecolor', 'none');
            
                 bar(1:nTypes, d(3, :), width, ...
                'facecolor', 'none', ...
                'edgecolor', colors{3}, ...
                'linewidth', 2, ...
                'linestyle', ':');
            
            legend('Young', 'Elderly', 'Experimental', ...
                'box', 'off', ...
                'fontsize', fontSize, ...
                'location', 'northeast');
   
    end
    
    % print
    if printFigures
        if ~isfolder('figures')
            !mkdir figures
        end
        print(sprintf('figures/%s.eps', figureList{figureIdx}), '-depsc');
        print(sprintf('figures/%s.png', figureList{figureIdx}), '-dpng');
    end
    
end